"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _customer_home_products from './customer-home-products.bones.json'
import _customer_catalog_products from './customer-catalog-products.bones.json'

configureBoneyard({"color":"#f1dfcf","animate":"shimmer","shimmerColor":"#fff8f1","speed":"1.7s","shimmerAngle":105,"stagger":35,"transition":180})

registerBones({
  "customer-home-products": _customer_home_products,
  "customer-catalog-products": _customer_catalog_products,
})
